name: Org Test

on:
  workflow_dispatch

jobs:
    org:
        runs-on: ubuntu-latest
        environment:
          name: production
        steps:
          - name: Print Org github repo test message
            run: echo "Successful"